name: Executar testes

on:
# execute esse workflow sempre que subir a alteração para a branch master
  push:
    branches: [ "master" ]

jobs:
  build:
  # maquina onde o workflow será executado
    runs-on: ubuntu-latest

    strategy:
      matrix:
      # vai executar 2x o mesmo workflow [paralelo] para cada node-version
        node-version: [12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        npm install
        npx cypress run
