name: Executando testes

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Configurando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalando as dependências
        run: |
          npm install 
          npm install -D cypress@9.1

      - name: Executando os testes com cypress
        run: npx cypress run
