name: Executando testes

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Instalando o Node.js e o Cypress
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalando as dependências
        run: npm install

      - name: Executando os testes com cypress
        run: npx cypress run
