name: Executar testes

on:
# execute esse workflow sempre que subir a alteração para a branch master
  push:
    branches: [ "master" ]

jobs:
  build:
  # maquina onde o workflow será executado
    runs-on: ubuntu-latest

    strategy:
      matrix:
      # vai executar 2x o mesmo workflow [paralelo] para cada node-version
        node-version: [12.x]
        
    steps:
    - name: instalando o node e cypress
    - uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        npm install
        npx cypress run
        
    - name: Create dir for report
    - run: mkdir testArtifacts

    - name: Install Newman
      run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

    - name: Run Test
      run: newman run ServRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra

    - name: Report
      uses: actions/upload-artifact@v2
      with: 
         name: Reports
         path: newman
